baseURL = 'https://steven.kreuzer.cx/'
languageCode = 'en-us'
title = 'Steven Kreuzer'
theme = 'archie'
copyright = "© Steven Kreuzer"
paginate = 3

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/skreuzer"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/skreuzer"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/skreuzer"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
